<?php
    session_start();
    unset($_SESSION['id']);
    unset($_SESSION['fname']);
    unset($_SESSION['lname']);
    unset($_SESSION['uname']);
    unset($_SESSION['email']);
    session_destroy();
    header('Location:login.php');
?> 