<?php
use PHPMailer\PHPMailer\PHPMailer;
function updateBookStatus(){
    require 'public/connection.php';
    if(isset($_SERVER["REQUEST_METHOD"]) == "POST"){
        if(isset($_POST['btn-update'])){
            date_default_timezone_set("Asia/Manila");
            $customerName = $_POST['customerName'];
            $refNumber = $_POST['refNumber'];
            $id = $_POST['id'];
            $email = $_POST['email'];
            $createAt = $_POST['reservedDate'];
            $bookStatus = $_POST['bookStatus'];
            $guests = $_POST['guests'];
            $schedDate = date('M-d-Y',strtotime($_POST['schedDate']));
            $schedTime = $_POST['schedTime'];
            $notifDate = date('Y-m-d h:i:s');
            $firstLetter = substr($customerName,0,1);
            $logo = "https://i.ibb.co/CMq6CXs/logo.png";
            require 'php-mailer/vendor/autoload.php';
            $mail = new PHPMailer;
            $mail->isSMTP();
            $mail->Host = 'smtp.gmail.com';
            $mail->SMTPAuth = true;
            $mail->Username = 'mangmacspizzahouse@gmail.com';
            $mail->Password = 'ylzikpnelhxltves'; 
            $mail->SMTPSecure = 'tls';
            $mail->Port = 587;
            $mail->setFrom('mangmacspizzahouse@gmail.com', "Mang Mac's Marinero");
            $mail->addAddress($email);
            $mail->isHTML(true);
            if($bookStatus == "Reserved"){
                $updateOrderStatus = $connect->prepare("UPDATE tblorderdetails SET order_status=? WHERE order_number=?");
                $updateOrderStatus->bind_param('ss',$bookStatus,$refNumber);
                $updateOrderStatus->execute();
                $updateBookStatus = $connect->prepare("UPDATE tblreservation SET status=? WHERE id=?");
                $updateBookStatus->bind_param('si',$bookStatus,$id);
                $updateBookStatus->execute();
                if($updateBookStatus){
                    function pushNotifcation($sendTo,$data){
                        $apiKey = "AAAAozYNVDs:APA91bFDRuJDQZCnFaAmQFP_uTUUzp9fYQZRJI01XtZ34XYr1ifB2f7jDa1R7WVxavsv-hSZZ7qivrEUk37O7-s1VcB8wMJuhIW0R6-ldwv9UQnxlJssMGvEdOq7admem2vfrCkAUqo2";
                        $url = "https://fcm.googleapis.com/fcm/send";
                        $fields = json_encode(array('to'=>$sendTo,'notification'=>$data));
                        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                        $ch = curl_init();
                        curl_setopt($ch, CURLOPT_URL,$url);
                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                        curl_setopt($ch, CURLOPT_POST, 1);
                        curl_setopt($ch, CURLOPT_POSTFIELDS,($fields));
                    
                        $headers = array();
                        $headers[] = 'Authorization:key='.$apiKey;
                        $headers[] = 'Content-Type: application/json';
                        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                    
                        $result = curl_exec($ch);
                        if (curl_errno($ch)) {
                            echo 'Error:' . curl_error($ch);
                        }
                        curl_close($ch);
                        }
                        $sendTo = $_POST['token'];
                        $data = array(
                            'title'=>"$bookStatus",
                            'body'=>"Hello $customerName,\nyour table reservation for $guests guests  is already confirmed. See you at $schedDate - $schedTime"
                        );
                        pushNotifcation($sendTo,$data);
                        $mail->Subject = "Your Booking #".$refNumber." has been confirmed";
                        $mail->Body = "
                        <div class='container' style='padding: 1rem;'>
                        <div style='display: flex; flex-direction: column; align-items: center;'>
                            <div class='logo-section'>
                                <img src='$logo' width='50'>
                                <strong>Mang Macs's Food Shop</strong>
                            </div>
                            <div class='icon-section' style='padding: 1rem;'>
                                <i class='fa-regular fa-circle-check'></i>
                            </div>
                            <div style='text-align: center;'>
                                <p>Hello ".$customerName."</p>
                                <h3>Your table reservation for ".$guests." guests is already confirmed. See you at </h3> 
                            </div>
                        </div>
                        <hr style='border:0.3px solid #dbdbdb;'>
                        <div>
                            <strong>Booking Summary</strong>
                        </div>
                        <div style = 'style:display:flex; flex-direction:column;'>
                            <div style='display: flex; justify-content: space-between;'>
                                <p style='width:150px;'>Booking Number:</p>
                                <p>".$refNumber."</p>
                            </div>
                            <div style='display: flex; justify-content: space-between; margin: -20px 0;'>
                                <p style='width:150px;'>Guests:</p>
                                <p>".$guests."</p>
                            </div>
                            <div style='display: flex; justify-content: space-between; margin: -20px 0;'>
                                <p style='width:150px;'>Schedule:</p>
                                <p>".$schedDate." ".$schedTime."</p>
                            </div> 
                            <div style='display: flex; justify-content: space-between;'>
                                <p style='width:150px;'>Reminder</p><br>
                                <p style='text-align:center'>Don't be an hour late, please. 
                                Your table reservation will be canceled 
                                if you arrive more than 30 minutes late.</p>
                            </div>
                        </div>
                        <hr style='border:0.3px solid #dbdbdb;'>
                        <div style='text-align:center';>
                            <p>from</p></br>
                            <h3>Mang Mac' s Food Shop</h3></br>
                            <p>Zone 5, Barangay Sta. Lucia Bypass Road, Urdaneta, Philippines</p>
                        </div>
                    </div>
                    ";
                    $mail->AltBody = 'FROM: mangmacspizzahouse@gmail.com';
                    $mail->send();
                    header('Location:reservation.php');
                    //put another mail here
                }
            }
            else if($bookStatus == "Cancelled"){
                $updateOrderStatus = $connect->prepare("UPDATE tblorderdetails SET order_status=? WHERE order_number=?");
                $updateOrderStatus->bind_param('ss',$bookStatus,$refNumber);
                $updateOrderStatus->execute();
                $updateBookStatus = $connect->prepare("UPDATE tblreservation SET status=? WHERE id=?");
                $updateBookStatus->bind_param('si',$bookStatus,$id);
                $updateBookStatus->execute();
                if($updateBookStatus){
                    function pushNotifcation($sendTo,$data){
                        $apiKey = "AAAAozYNVDs:APA91bFDRuJDQZCnFaAmQFP_uTUUzp9fYQZRJI01XtZ34XYr1ifB2f7jDa1R7WVxavsv-hSZZ7qivrEUk37O7-s1VcB8wMJuhIW0R6-ldwv9UQnxlJssMGvEdOq7admem2vfrCkAUqo2";
                        $url = "https://fcm.googleapis.com/fcm/send";
                        $fields = json_encode(array('to'=>$sendTo,'notification'=>$data));
                        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                        $ch = curl_init();
                        curl_setopt($ch, CURLOPT_URL,$url);
                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                        curl_setopt($ch, CURLOPT_POST, 1);
                        curl_setopt($ch, CURLOPT_POSTFIELDS,($fields));
                    
                        $headers = array();
                        $headers[] = 'Authorization:key='.$apiKey;
                        $headers[] = 'Content-Type: application/json';
                        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                    
                        $result = curl_exec($ch);
                        if (curl_errno($ch)) {
                            echo 'Error:' . curl_error($ch);
                        }
                        curl_close($ch);
                        }
                        $sendTo = $_POST['token'];
                        $data = array(
                            'title'=>"$bookStatus",
                            'body'=>"Hello $customerName,\nsorry, there is no available table for accomodation."
                        );
                        pushNotifcation($sendTo,$data);
                        $mail->Subject = "Your reservation #".$refNumber." is not available";
                        $mail->Body = "
                        <div class='container' style='padding: 1rem;'>
                        <div style='display: flex; flex-direction: column; align-items: center;'>
                            <div class='logo-section'>
                                <img src='$logo' width='50'>
                                <strong>Mang Macs's Food Shop</strong>
                            </div>
                            <div class='icon-section' style='padding: 1rem;'>
                                <i class='fa-regular fa-circle-check'></i>
                            </div>
                            <div style='text-align: center;'>
                                <p>Hello ".$customerName."</p>
                                <h3>Sorry, there is no available table for accomodation.</h3> 
                            </div>
                        </div>
                        <hr style='border:0.3px solid #dbdbdb;'>
                        <div>
                            <strong>Booking Summary</strong>
                        </div>
                        <div style = 'style:display:flex; flex-direction:column;'>
                            <div style='display: flex; justify-content: space-between;'>
                                <p style='width:150px;'>Booking Number:</p>
                                <p>".$refNumber."</p>
                            </div>
                            <div style='display: flex; justify-content: space-between; margin: -20px 0;'>
                                <p style='width:150px;'>Guests:</p>
                                <p>".$guests."</p>
                            </div>
                            <div style='display: flex; justify-content: space-between; margin: -20px 0;'>
                                <p style='width:150px;'>Schedule:</p>
                                <p>".$schedDate." ".$schedTime."</p>
                            </div> 
                        </div>
                        <hr style='border:0.3px solid #dbdbdb;'>
                        <div style='text-align:center';>
                            <p>from</p></br>
                            <h3>Mang Mac' s Food Shop</h3></br>
                            <p>Zone 5, Barangay Sta. Lucia Bypass Road, Urdaneta, Philippines</p>
                        </div>
                    </div>
                    ";
                    $mail->AltBody = 'FROM: mangmacspizzahouse@gmail.com';
                    $mail->send();
                    header('Location:reservation.php');
                }
            }
            else{
                $completedTime = date('Y-m-d h:i:s');
                //update order status to order completed in table `tblorderdetails`
                $updateOrderStatus = $connect->prepare("UPDATE tblorderdetails SET order_status=?,completed_time=? WHERE order_number=?");
                $updateOrderStatus->bind_param('sss',$bookStatus,$completedTime,$refNumber);
                $updateOrderStatus->execute();
                //update booking status to finished in table `tblreservation`
                $updateBookStatus = $connect->prepare("UPDATE tblreservation SET status=? WHERE id=?");
                $updateBookStatus->bind_param('si',$bookStatus,$id);
                $updateBookStatus->execute();
                header('Location:reservation.php');
               
            }
        }
    }
}
function noShowsReservation(){
    //update table reservation status to No shows when the customers did not arrive
    require 'public/connection.php';
    $reserved = 'Reserved';
    $noShows = 'No Shows';
    $bookingNumber = array();
    $email = array();
    $customerName = array();
    $guests = array();
    $scheduledDate = array();
    $getId = $connect->query("SELECT * FROM tblreservation WHERE 
    STR_TO_DATE(CONCAT(scheduled_date,' ',scheduled_time), '%Y-%m-%d %h:%i %p') <= 
    DATE_SUB(NOW(),INTERVAL 1 HOUR) AND status='Reserved'");
    while($fetch = $getId->fetch_assoc()){
        $bookingNumber[] =  $fetch['refNumber'];
        $email[] = $fetch['email'];
        $customerName[] = $fetch['fname']." ".$fetch['lname'];
        $guests[] = $fetch['guests'];
        $scheduledDate[] = $fetch['scheduled_date']." ".$fetch['scheduled_time'];
    }
   foreach($bookingNumber as $index => $orderNumber){
        $newOrderNumber = $orderNumber;
        $newEmail = $email[$index];
        $newCustomerName = $customerName[$index];
        $newGuests = $guests[$index];
        $newSched = $scheduledDate[$index];
        $logo = "https://i.ibb.co/CMq6CXs/logo.png";
        $updateRemoveStat = $connect->prepare("UPDATE tblreservation SET status=? WHERE refNumber=?");
        $updateRemoveStat->bind_param('ss',$noShows,$newOrderNumber);
        echo $connect->error;
        require 'php-mailer/vendor/autoload.php';
        $mail = new PHPMailer;
        $mail->isSMTP();
        $mail->Host = 'smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'mangmacspizzahouse@gmail.com';
        $mail->Password = 'ylzikpnelhxltves'; 
        $mail->SMTPSecure = 'tls';
        $mail->Port = 587;
        $mail->setFrom('mangmacspizzahouse@gmail.com', "Mang Mac's Marinero");
        $mail->addAddress($newEmail);
        $mail->isHTML(true);
        if($updateRemoveStat->execute()){
            $mail->Subject = "Your reservation #".$newOrderNumber." is not available";
            $mail->Body = "
            <div class='container' style='padding: 1rem;'>
            <div style='display: flex; flex-direction: column; align-items: center;'>
                <div class='logo-section'>
                    <img src='$logo' width='50'>
                    <strong>Mang Macs's Food Shop</strong>
                </div>
                <div class='icon-section' style='padding: 1rem;'>
                    <i class='fa-regular fa-circle-check'></i>
                </div>
                <div style='text-align: center;'>
                    <p>Hello ".$newCustomerName."</p>
                    <h3>Due to your delayed arrival on the scheduled date and time, we have now decided to cancel your table reservation.</h3> 
                </div>
            </div>
            <hr style='border:0.3px solid #dbdbdb;'>
            <div>
                <strong>Booking Summary</strong>
            </div>
            <div style = 'style:display:flex; flex-direction:column;'>
                <div style='display: flex; justify-content: space-between;'>
                    <p style='width:150px;'>Booking Number:</p>
                    <p>".$newOrderNumber."</p>
                </div>
                <div style='display: flex; justify-content: space-between; margin: -20px 0;'>
                    <p style='width:150px;'>Guests:</p>
                    <p>".$newGuests."</p>
                </div>
                <div style='display: flex; justify-content: space-between; margin: -20px 0;'>
                    <p style='width:150px;'>Schedule:</p>
                    <p>$newSched</p>
                </div> 
            </div>
            <hr style='border:0.3px solid #dbdbdb;'>
            <div style='text-align:center';>
                <p>from</p></br>
                <h3>Mang Mac' s Food Shop</h3></br>
                <p>Zone 5, Barangay Sta. Lucia Bypass Road, Urdaneta, Philippines</p>
            </div>
        </div>
        ";
        $mail->AltBody = 'FROM: mangmacspizzahouse@gmail.com';
        $mail->send();
        header('Location:reservation.php');
        }
    }  
}

updateBookStatus();
noShowsReservation();

?>
